-- MySQL Script generated by MySQL Workbench
-- 10/20/15 12:55:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema master_quadrum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `master_quadrum` ;

-- -----------------------------------------------------
-- Schema master_quadrum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `master_quadrum` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `master_quadrum` ;

-- -----------------------------------------------------
-- Table `master_quadrum`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`rol` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`rol` (
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`usuario` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`usuario` (
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `enable` TINYINT(1) NOT NULL,
  `nombre` VARCHAR(145) NOT NULL,
  `rol` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`correo`),
  INDEX `fk_usuario_rol_idx` (`rol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `master_quadrum`.`rol` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`empleado` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`empleado` (
  `id` INT UNSIGNED NOT NULL,
  `num_empleado` VARCHAR(45) NULL,
  `usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_empleado_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `master_quadrum`.`usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`tipo_regimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`tipo_regimen` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`tipo_regimen` (
  `id` INT(2) UNSIGNED NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`cliente` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`cliente` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(13) NOT NULL,
  `correo_contacto` VARCHAR(100) NULL,
  `telefono_contacto` VARCHAR(20) NULL,
  `tipo_regimen` INT(2) UNSIGNED NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_tipo_regimen1_idx` (`tipo_regimen` ASC),
  INDEX `fk_cliente_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_cliente_tipo_regimen1`
    FOREIGN KEY (`tipo_regimen`)
    REFERENCES `master_quadrum`.`tipo_regimen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `master_quadrum`.`usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`categoria_pistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`categoria_pistas` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`categoria_pistas` (
  `id` INT(2) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`pistas_auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`pistas_auditoria` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`pistas_auditoria` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(20) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `categoria` INT(2) UNSIGNED NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pistas_auditoria_categoria1_idx` (`categoria` ASC),
  INDEX `fk_pistas_auditoria_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_pistas_auditoria_categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `master_quadrum`.`categoria_pistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pistas_auditoria_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `master_quadrum`.`usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`categoria_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`categoria_tickets` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`categoria_tickets` (
  `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`ticket` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`ticket` (
  `id` INT(5) UNSIGNED NOT NULL,
  `titulo` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(266) NOT NULL,
  `fecha` DATE NOT NULL,
  `categoria_tickets` INT(2) UNSIGNED NOT NULL,
  `cliente` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_categoria_tickets1_idx` (`categoria_tickets` ASC),
  INDEX `fk_ticket_cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_ticket_categoria_tickets1`
    FOREIGN KEY (`categoria_tickets`)
    REFERENCES `master_quadrum`.`categoria_tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `master_quadrum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`cliente_contribuyente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`cliente_contribuyente` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`cliente_contribuyente` (
  `cliente` INT(5) UNSIGNED NOT NULL,
  `contribuyente` INT(5) UNSIGNED NOT NULL,
  `borrar` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente`, `contribuyente`),
  INDEX `fk_cliente_has_cliente_cliente2_idx` (`contribuyente` ASC),
  INDEX `fk_cliente_has_cliente_cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_cliente_has_cliente_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `master_quadrum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_cliente_cliente2`
    FOREIGN KEY (`contribuyente`)
    REFERENCES `master_quadrum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`domicilio` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`domicilio` (
  `id` INT(5) UNSIGNED NOT NULL,
  `calle` VARCHAR(175) NOT NULL,
  `estado` VARCHAR(175) NOT NULL,
  `pais` VARCHAR(175) NOT NULL,
  `municipio` VARCHAR(175) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `num_interior` VARCHAR(175) NULL,
  `num_exterior` VARCHAR(175) NULL,
  `localidad` VARCHAR(175) NULL,
  `referencia` VARCHAR(175) NULL,
  `colonia` VARCHAR(175) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_domicilio_cliente1`
    FOREIGN KEY (`id`)
    REFERENCES `master_quadrum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`csd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`csd` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`csd` (
  `rfc` VARCHAR(13) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `cer` BLOB NOT NULL,
  `llave` BLOB NOT NULL,
  `cliente` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`rfc`),
  INDEX `fk_csd_cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_csd_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `master_quadrum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`historial_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`historial_pago` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`historial_pago` (
  `id` INT(6) NOT NULL AUTO_INCREMENT,
  `costo` DECIMAL(3,2) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `limite_timbres` INT(11) NOT NULL,
  `timbres_exedidos` INT(11) NOT NULL,
  `importe_total` DECIMAL(8,2) NOT NULL,
  `fecha_pago` DATE NULL,
  `cliente` INT(5) UNSIGNED NOT NULL,
  `contribuyente` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_pago_cliente_contribuyente1_idx` (`cliente` ASC, `contribuyente` ASC),
  CONSTRAINT `fk_historial_pago_cliente_contribuyente1`
    FOREIGN KEY (`cliente` , `contribuyente`)
    REFERENCES `master_quadrum`.`cliente_contribuyente` (`cliente` , `contribuyente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`acuse_otros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`acuse_otros` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`acuse_otros` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acuse_cancelacion` VARCHAR(45) NOT NULL,
  `cliente` INT(5) UNSIGNED NOT NULL,
  `contribuyente` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acuse_otros_cliente_contribuyente1_idx` (`cliente` ASC, `contribuyente` ASC),
  CONSTRAINT `fk_acuse_otros_cliente_contribuyente1`
    FOREIGN KEY (`cliente` , `contribuyente`)
    REFERENCES `master_quadrum`.`cliente_contribuyente` (`cliente` , `contribuyente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`cfdi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`cfdi` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`cfdi` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(60) NOT NULL,
  `fecha_timbrado` DATETIME NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  `receptor` VARCHAR(13) NOT NULL,
  `importe` DECIMAL(10,2) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `sha` VARCHAR(1045) NOT NULL,
  `cliente` INT(5) UNSIGNED NOT NULL,
  `contribuyente` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cfdi_cliente_contribuyente1_idx` (`cliente` ASC, `contribuyente` ASC),
  CONSTRAINT `fk_cfdi_cliente_contribuyente1`
    FOREIGN KEY (`cliente` , `contribuyente`)
    REFERENCES `master_quadrum`.`cliente_contribuyente` (`cliente` , `contribuyente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`pendiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`pendiente` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`pendiente` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pendiente_cfdi1`
    FOREIGN KEY (`id`)
    REFERENCES `master_quadrum`.`cfdi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`acuse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`acuse` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`acuse` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `acuse_timbrado` TEXT NOT NULL,
  `acuse_cancelado` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_acuse_cfdi1`
    FOREIGN KEY (`id`)
    REFERENCES `master_quadrum`.`cfdi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`xml_timbrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`xml_timbrado` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`xml_timbrado` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `recibo_timbrado` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_xml_timbrado_cfdi1`
    FOREIGN KEY (`id`)
    REFERENCES `master_quadrum`.`cfdi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_quadrum`.`lco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_quadrum`.`lco` ;

CREATE TABLE IF NOT EXISTS `master_quadrum`.`lco` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `num_certificado` VARCHAR(50) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  `oblicaciones` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
