package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name = "archivo", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class Archivo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Min(value = 1, message = "El archivo debe ser mayor a cero")
    @Getter @Setter private Integer id;

    @Column(name = "numeroEmpresa", nullable = false)
    @Getter @Setter private Integer numeroEmpresa;
    
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    @Column(name = "inicio", nullable = false)
    @Getter @Setter private Date inicio;
    
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    @Column(name = "fin", nullable = true)
    @Getter @Setter private Date fin;
//
//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "archivo")
//    @Getter @Setter private List<Recibo> recibos;


}
