package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import static com.quadrum.nominas2.entidades.ExpRegulares.NOMBRES;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;
/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class Banco implements java.io.Serializable {
 
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private int id;    
    
    @Pattern(regexp = NOMBRES + "36}", message = "El Nombre del Banco no puede ser vacio")
    @Column(name = "nombre", nullable = false, length = 37)
    @Getter @Setter private String nombre;
    
    @Pattern(regexp = NOMBRES + "117}", message = "La Razón Social del Banco no puede ser vacia")
    @Column(name = "razon_social", nullable = false, length = 118)
    @Getter @Setter private String razonSocial;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
    @Getter @Setter private List<InformacionOpcional> informacionOpcionals;

    public Banco(int id, String nombre, String razonSocial) {
        this.id = id;
        this.nombre = nombre;
        this.razonSocial = razonSocial;
    }
}
