package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import static com.quadrum.nominas2.entidades.ExpRegulares.NOMBRES;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;
/**
 * Deduccion generated by hbm2java
 */
@Entity
@Table(name = "deduccion", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public class Deduccion implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private int id;

    @Column(name = "nombre", nullable = false, length = 87)
    @Pattern(regexp = NOMBRES + "87}", message = "El nombre deebn ser solo letras")
    @Getter @Setter private String nombre;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "deduccion")
    @Getter @Setter private List<DeduccionEmpresa> deduccionEmpresas;

    public Deduccion(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

}
