package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public @Data  class Empleado implements java.io.Serializable {

    @Id
    @Column(name = "curp", unique = true, nullable = false, length = 45)
    private String curp;

   @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario")
    private Usuario usuario;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    private List<Recibo> recibos;


}
