package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "nomifast", uniqueConstraints = @UniqueConstraint(columnNames = "rfc"))
@AllArgsConstructor
@NoArgsConstructor
public @Data class Empresa implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "regimen_fiscal", nullable = false)
    private RegimenFiscal regimenFiscal;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    private Usuario usuario;

    @Column(name = "razon_social", nullable = false, length = 45)
    private String razonSocial;

    @Column(name = "folios", nullable = false)
    private int folios;

    @Column(name = "ilimitados", nullable = false)
    private boolean ilimitados;

    @Column(name = "configuracion_inicial", nullable = false)
    private int configuracionInicial;

    @Column(name = "acceso_por_sucursales", nullable = false)
    private boolean accesoPorSucursales;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    private List<Sucursal> sucursals;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    private List<PercepcionEmpresa> percepcionEmpresas;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    private List<DeduccionEmpresa> deduccionEmpresas;

    public Empresa(RegimenFiscal regimenFiscal, String razonSocial, int folios, boolean ilimitados, int configuracionInicial, boolean accesoPorSucursales) {
        this.regimenFiscal = regimenFiscal;
        this.razonSocial = razonSocial;
        this.folios = folios;
        this.ilimitados = ilimitados;
        this.configuracionInicial = configuracionInicial;
        this.accesoPorSucursales = accesoPorSucursales;
    }

}
