package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.Valid;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "nomifast")//, uniqueConstraints = @UniqueConstraint(columnNames = "rfc"))
@AllArgsConstructor
@NoArgsConstructor
public class Empresa implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Valid
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "regimen_fiscal", nullable = false)
    @Getter @Setter private RegimenFiscal regimenFiscal;

    @Valid
    @OneToOne(fetch = FetchType.LAZY,  cascade = {CascadeType.MERGE, CascadeType.REFRESH})
    @JoinColumn(name = "usuario", nullable = false)
    @Getter @Setter private Usuario usuario;

    @Column(name = "folios", nullable = false)
    @Getter @Setter private int folios;

    @Column(name = "ilimitados", nullable = false)
    @Getter @Setter private boolean ilimitados;

    @Column(name = "configuracion_inicial", nullable = false)
    @Getter @Setter private int configuracionInicial;

    @Column(name = "acceso_por_sucursales", nullable = false)
    @Getter @Setter private boolean accesoPorSucursales;
    
    @Column(name = "archivosTimbrados", nullable = false)
    @Getter @Setter private int archivosTimbrados;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    @Getter @Setter private List<Sucursal> sucursals;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    @Getter @Setter private List<PercepcionEmpresa> percepcionEmpresas;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    @Getter @Setter private List<DeduccionEmpresa> deduccionEmpresas;

    public Empresa(RegimenFiscal regimenFiscal, int folios, boolean ilimitados, int configuracionInicial, boolean accesoPorSucursales) {
        this.regimenFiscal = regimenFiscal;
        this.folios = folios;
        this.ilimitados = ilimitados;
        this.configuracionInicial = configuracionInicial;
        this.accesoPorSucursales = accesoPorSucursales;
    }

}
