package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * InformacionOpcional generated by hbm2java
 */
@Entity
@Table(name = "informacion_opcional", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public @Data  class InformacionOpcional implements java.io.Serializable {

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "recibo"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "riesgo_puesto")
    private RiesgoPuesto riesgoPuesto;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Recibo recibo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "banco")
    private Banco banco;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inico_laboral", length = 10)
    private Date fechaInicoLaboral;

    @Column(name = "departamento", length = 45)
    private String departamento;

    @Column(name = "tipo_contrato", length = 45)
    private String tipoContrato;

    @Column(name = "tipo_jornada", length = 45)
    private String tipoJornada;

    @Column(name = "salario_base", precision = 10)
    private BigDecimal salarioBase;

    @Column(name = "salario_diario", precision = 10)
    private BigDecimal salarioDiario;

    @Column(name = "clabe", length = 45)
    private String clabe;

    @Column(name = "antiguedad")
    private Integer antiguedad;

    @Column(name = "puesto", length = 45)
    private String puesto;

    @Column(name = "faltas")
    private Integer faltas;

    public InformacionOpcional(Recibo recibo) {
        this.recibo = recibo;
    }

}
