package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * PercepcionEmpresa generated by hbm2java
 */
@Entity
@Table(name = "percepcion_empresa", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public @Data  class PercepcionEmpresa implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "percepcion", column = @Column(name = "percepcion", nullable = false)),
        @AttributeOverride(name = "empresa", column = @Column(name = "EMPRESA", nullable = false))})
    private PercepcionEmpresaId id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "percepcion", nullable = false, insertable = false, updatable = false)
    private Percepcion percepcion;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPRESA", nullable = false, insertable = false, updatable = false)
    private Empresa empresa;

    @Column(name = "borrar", length = 45)
    private String borrar;

    public PercepcionEmpresa(PercepcionEmpresaId id, Percepcion percepcion, Empresa empresa) {
        this.id = id;
        this.percepcion = percepcion;
        this.empresa = empresa;
    }

}
