package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import static com.quadrum.nominas2.entidades.ExpRegulares.NOMBRES;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;
/**
 * PeriodicidadPago generated by hbm2java
 */
@Entity
@Table(name = "periodicidad_pago", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class PeriodicidadPago implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    @Pattern(regexp = NOMBRES + "286}", message = "El nombre deben ser solo letras")
    @Getter @Setter private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidadPago")
    @Getter @Setter private List<Recibo> recibos;

    public PeriodicidadPago(String nombre) {
        this.nombre = nombre;
    }

}
