package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name = "recibo", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public @Data  class Recibo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "periodicidad_pago", nullable = false)
    private PeriodicidadPago periodicidadPago;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empleado", nullable = false)
    private Empleado empleado;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sucursal", nullable = false)
    private Sucursal sucursal;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "regimen_contratacion", nullable = false)
    private RegimenContratacion regimenContratacion;

    @Column(name = "num_empleado", nullable = false, length = 45)
    private String numEmpleado;

    @Column(name = "uuid", nullable = false, length = 45)
    private String uuid;

    @Column(name = "registro_patronal", nullable = false)
    private int registroPatronal;

    @Temporal(TemporalType.DATE)
    @Column(name = "fehca_pago", nullable = false, length = 10)
    private Date fehcaPago;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_final_pago", nullable = false, length = 10)
    private Date fechaFinalPago;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicial_pago", nullable = false, length = 10)
    private Date fechaInicialPago;

    @Column(name = "numero_dias_pagados", nullable = false)
    private int numeroDiasPagados;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_timbrado", nullable = false, length = 10)
    private Date fechaTimbrado;

    @Column(name = "recibo", nullable = false, length = 65535)
    private String recibo;

    @Column(name = "acuse", nullable = false, length = 65535)
    private String acuse;

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "recibo")
    private InformacionOpcional informacionOpcional;

    public Recibo(PeriodicidadPago periodicidadPago, Empleado empleado, Sucursal sucursal, RegimenContratacion regimenContratacion, String numEmpleado, String uuid, int registroPatronal, Date fehcaPago, Date fechaFinalPago, Date fechaInicialPago, int numeroDiasPagados, Date fechaTimbrado, String recibo, String acuse) {
        this.periodicidadPago = periodicidadPago;
        this.empleado = empleado;
        this.sucursal = sucursal;
        this.regimenContratacion = regimenContratacion;
        this.numEmpleado = numEmpleado;
        this.uuid = uuid;
        this.registroPatronal = registroPatronal;
        this.fehcaPago = fehcaPago;
        this.fechaFinalPago = fechaFinalPago;
        this.fechaInicialPago = fechaInicialPago;
        this.numeroDiasPagados = numeroDiasPagados;
        this.fechaTimbrado = fechaTimbrado;
        this.recibo = recibo;
        this.acuse = acuse;
    }

}
