package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name = "recibo", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class Recibo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "archivo", nullable = false)
    @Getter @Setter private Archivo archivo;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "empleado", nullable = false)
    @Getter @Setter private Empleado empleado;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sucursal", nullable = false)
    @Getter @Setter private Sucursal sucursal;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "regimen_contratacion", nullable = false)
    @Getter @Setter private RegimenContratacion regimenContratacion;

    @Column(name = "num_empleado", nullable = false, length = 45)
    @Getter @Setter private String numEmpleado;

    @Column(name = "uuid", nullable = false, length = 45)
    @Getter @Setter private String uuid;
    
    @Column(name = "periodicidad_pago", nullable = false, length = 195)
    @Getter @Setter private String periodicidadPago;

    @Column(name = "registro_patronal", nullable = false)
    @Getter @Setter private int registroPatronal;

    @Temporal(TemporalType.DATE)
    @Column(name = "fehca_pago", nullable = false, length = 10)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Getter @Setter private Date fehcaPago;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_final_pago", nullable = false, length = 10)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Getter @Setter private Date fechaFinalPago;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicial_pago", nullable = false, length = 10)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Getter @Setter private Date fechaInicialPago;

    @Column(name = "numero_dias_pagados", nullable = false)
    @Getter @Setter private int numeroDiasPagados;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_timbrado", nullable = false, length = 10)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Getter @Setter private Date fechaTimbrado;

    @Column(name = "recibo", nullable = false, length = 65535)
    @Getter @Setter private String reciboXML;

    @Column(name = "acuse", nullable = false, length = 65535)
    @Getter @Setter private String acuse;

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "recibo")
    @Getter @Setter private InformacionOpcional informacionOpcional;
    
    @Column(name = "totalPagar", precision = 12)
    @Getter @Setter private BigDecimal totalPagar;

    public Recibo(Empleado empleado, Sucursal sucursal, RegimenContratacion regimenContratacion, String numEmpleado, String uuid, int registroPatronal, Date fehcaPago, Date fechaFinalPago, Date fechaInicialPago, int numeroDiasPagados, Date fechaTimbrado, String recibo, String acuse) {
        this.empleado = empleado;
        this.sucursal = sucursal;
        this.regimenContratacion = regimenContratacion;
        this.numEmpleado = numEmpleado;
        this.uuid = uuid;
        this.registroPatronal = registroPatronal;
        this.fehcaPago = fehcaPago;
        this.fechaFinalPago = fechaFinalPago;
        this.fechaInicialPago = fechaInicialPago;
        this.numeroDiasPagados = numeroDiasPagados;
        this.fechaTimbrado = fechaTimbrado;
        this.reciboXML = recibo;
        this.acuse = acuse;
    }

}
