package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import static com.quadrum.nominas2.entidades.ExpRegulares.NOMBRES;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;
/**
 * RegimenFiscal generated by hbm2java
 */
@Entity
@Table(name = "regimen_fiscal", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class RegimenFiscal implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Min(value = 1, message = "Debe seleccionar una opción")
    @Getter @Setter private Integer id;

    @Pattern(regexp = NOMBRES + "45}", message = "EL nombre deben ser solo letras")
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "regimenFiscal")
    @Getter @Setter private List<Empresa> empresas;

    public RegimenFiscal(Integer id) {
        this.id = id;
    }

}
