package com.quadrum.nominas2.entidades;
// Generated 26/06/2015 12:29:26 PM by Hibernate Tools 3.6.0

import static com.quadrum.nominas2.entidades.ExpRegulares.NOMBRES;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;
/**
 * RiesgoPuesto generated by hbm2java
 */
@Entity
@Table(name = "riesgo_puesto", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public  class RiesgoPuesto implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private int id;

    @Pattern(regexp = NOMBRES + "45}", message = "EL nombre deben ser solo letras")
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "riesgoPuesto")
    @Getter @Setter private List<InformacionOpcional> informacionOpcionals;

    public RiesgoPuesto(int id) {
        this.id = id;
    }

}
