package com.quadrum.nominas2.entidades;
// Generated 7/07/2015 11:49:50 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;import lombok.Setter;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public class Rol implements java.io.Serializable {

    @Id
    @Column(name = "rol", unique = true, nullable = false)
    @Getter @Setter private String rol;
    
    @Column(name = "descripcion", nullable = false, length = 145)
    @Getter @Setter private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    @Getter @Setter private List<RolUsuario> rolUsuarios;

    public Rol(String rol, String descripcion) {
        this.rol = rol;
        this.descripcion = descripcion;
    }


}
