package com.quadrum.nominas2.entidades;
// Generated 7/07/2015 11:49:50 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;import lombok.NoArgsConstructor;import lombok.Setter;

/**
 * RolUsuario generated by hbm2java
 */
@Entity
@Table(name = "rol_usuario", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public class RolUsuario implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "rol", column = @Column(name = "rol", nullable = false)),
        @AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false, length = 50))})
    @Getter @Setter private RolUsuarioId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol", nullable = false, insertable = false, updatable = false)
    @Getter @Setter private Rol rol;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false, insertable = false, updatable = false)
    @Getter @Setter private Usuario usuario;

    @Column(name = "borrar", length = 45)
    @Getter @Setter private String borrar;

    public RolUsuario(RolUsuarioId id, Rol rol, Usuario usuario) {
        this.id = id;
        this.rol = rol;
        this.usuario = usuario;
    }

}
