package com.quadrum.nominas2.entidades;
// Generated 7/07/2015 11:49:50 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "nomifast")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Usuario implements java.io.Serializable {

    @Id
    @Column(name = "user_name", unique = true, nullable = false, length = 50)
    private String userName;

    @Column(name = "password", nullable = false, length = 150)
    private String password;

    @Column(name = "enable", nullable = false)
    private boolean enable;

    @Column(name = "primera_sesion", nullable = false, length = 45)
    private String primeraSesion;

    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<Sucursal> sucursals;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<Empleado> empleados;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<Administrador> admins;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<RolUsuario> rolUsuarios;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<Empresa> empresas;

    public Usuario(String userName, String password, boolean enable, String primeraSesion, String nombre) {
        this.userName = userName;
        this.password = password;
        this.enable = enable;
        this.primeraSesion = primeraSesion;
        this.nombre = nombre;
    }

}
